### ISSUE TITLE
Job Type: Archive personal GitHub repos to Gitea

### ISSUE THREAD

**Issue by KennethWussmann** [KennethWussmann/github-archive#2]
With #1 github-archive is prepared to take different types of jobs. 

## WHY

I want to backup all the repos that I have at GitHub to a personal Gitea instance. I want github-archive to monitor what repos exist in my GitHub account and sync them to Gitea.

## WHAT

1. Create a new job type `repos`
2. That job, when run, should fetch all repos the given configured user has
3. Match repos found against the existing repos at Gitea
4. Create Gitea repo mirrors just like for starred repos, but for the repos found on the user account

### Configuration

Some configs that should be possible:

```YAML
jobs:
  - type: repos
    name: "My public repos"
    schedule: "*/10 * * * *"
    githubSource:
      # Notice that for purely public repos, no access token is required
      user: "KennethWussmann"
  - type: repos
    name: "My private & public repos"
    schedule: "*/10 * * * *"
    githubSource:
      accessTokens: "fill-me"
      user: "KennethWussmann"
  - type: repos
    name: "My private repos"
    schedule: "*/10 * * * *"
    githubSource:
      accessTokens: "fill-me"
      user: "KennethWussmann"
      filter: 
        visibility: # Usual default, private & public
         - private
  - type: repos
    name: "Someone's public repos"
    schedule: "*/10 * * * *"
    githubSource:
      user: "Someone"
```

All the currently supported mirror settings should continue to be supported for this job type as well.

## Out of scope
- Organization Support. Start with user-level archival first.
